[versions]
# App / SDK config
compileSdk = "36"
minSdk = "24"
targetSdk = "36"
versionCode = "3"
versionName = "1.0.2"

kotlin = "2.2.10"
core-ktx = "1.17.0"
kotlinx-serialization = "2.2.10"
kotlinx-serialization-json = "1.9.0"
kotlinx-serialization-retrofit = "1.0.0"
retrofit = "3.0.0"
okhttp3 = "5.1.0"
retrofit-scalars = "2.11.0"
android-plugin = "8.12.3"
lifecycle-runtime-ktx = "2.9.2"
material3 = "1.5.0-alpha02"
hilt = "2.57.1"
timber = "5.0.1"
datastore = "1.1.7"
compose-compiler = "1.5.15"
compose-activity = "1.10.1"
compose-viewmodel = "2.9.2"
compose-navigation = "2.9.3"
compose-navigation-hilt = "1.2.0"
compose = "1.9.0"
coil = "2.7.0"
junit = "4.13.2"
androidx-junit = "1.3.0"
espresso-core = "3.7.0"
ben-manes-versions = "0.52.0"
media3 = "1.4.1"

[libraries]
# Kotlin
kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

# Retrofit / OkHttp
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }
kotlinx-serialization-retrofit = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "kotlinx-serialization-retrofit" }
retrofit-scalars = { group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "retrofit-scalars" }

# Android
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }

# Compose
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
compose-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "compose-viewmodel" }
material = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation" }
compose-navigation-hilt = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "compose-navigation-hilt" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }

# Tools
coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "ben-manes-versions" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
